version: "2.25.0"

services:
  project_db:
    image: postgres:16
    container_name: project_postgres
    volumes:
      - ~/.pg/pg_data/test_dir:/var/lib/postgresql/data
    env_file:
      - .env
  TZ_Pavel_Shestakov_photo_point:
    image: tz_django:latest
    container_name: tz_django
    depends_on:
      - tz_django
    volumes:
      - static_volume:/test_dir/static
      - media_volume:/test_dir/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 soaqaz.wsgi:application"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: tz_nginx
    image: tz_nginx
    volumes:
      - static_volume:/test_dir/static
      - media_volume:/test_dir/media
    depends_on:
      - tz_django
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume: