# Generated by Django 5.0.1 on 2024-01-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_usd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentusd',
            name='date_request',
            field=models.DateField(default=None),
        ),
    ]
