# Generated by Django 5.0.1 on 2024-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_usd', '0003_alter_currentusd_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentusd',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
